services:
    server:
        build: .
        container_name: mycard-server
        ports:
            - "8080:8080"
        environment:
            DATABASE_URL: "host=db user=mycard password=mycard1234 dbname=mycard port=5432 sslmode=disable"
        depends_on:
            - db

    db:
        image: postgres:16
        container_name: mycard-db
        environment:
            POSTGRES_USER: mycard
            POSTGRES_PASSWORD: mycard1234
            POSTGRES_DB: mycard
        ports:
            - "5432:5432"
        volumes:
            - mycard-data:/var/lib/postgresql/data
volumes:
    mycard-data:
